/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaquotes;

import com.google.gson.Gson;
import org.junit.Assert;
import org.junit.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;

public class AppTest {
    @Test
    public void canGetRandomAuthorAndTextFromJson(){

        String filepath = "src/test/resources/test.json";
        String[] testLists = App.getResults(filepath);
        Assert.assertEquals(2, testLists.length);
        Assert.assertTrue("first position stores the author",testLists[0].contains("Author"));
        Assert.assertTrue("second position stores the text",testLists[1].contains("Text"));
    }
}
