/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaquotes;

import com.google.common.collect.Iterables;
import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import org.checkerframework.checker.units.qual.C;

import java.io.*;
import java.lang.reflect.Type;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
      String ss = getResults();
     System.out.println(ss);
    }

    public  static String getResults(){

        Gson gson = new Gson();
        String randomQutoe="";
        try{

            URL url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            BufferedReader br = new BufferedReader(new InputStreamReader((con.getInputStream())));
            QuoteApi quote = gson.fromJson(br,QuoteApi.class);
            randomQutoe=quote.getText();
//            System.out.println(quote.getText());
            //write to file

        }catch (IOException e){
            System.out.println(e);
            //read from json file
             String filepath = "src/main/resources/recentquotes.json";
             String res = getQuoteFromFile(filepath);
             randomQutoe = res;
        }
      return randomQutoe;
    }


    public  static String getQuoteFromFile(String filepath){
        Gson gson = new Gson();
        String qq = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader(filepath));
//https://stackoverflow.com/questions/34486503/read-a-json-file-with-gson-library,becuase json file start with "[" instead of"{"
            Type type = new TypeToken<List<Quote>>() {
            }.getType();
            List<Quote> quotes = gson.fromJson(br, type);
//go through the file created Quota class
//generate random index number
            Random randomNum = new Random();
            int sizeofList = quotes.size();
            int idx = randomNum.nextInt(sizeofList);
//change list to array--https://www.techiedelight.com/convert-list-to-array-java/
            Quote[] arr = Iterables.toArray(quotes, Quote.class);
            qq=arr[idx].getAuthor()+":"+arr[idx].getText();
        }
        catch (IOException e){
            System.out.println(e);
        }
        return qq;
    }


}
